WCR LMS/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WCR_LMS.DataContexts;
using System.Data;
using System.Data.Entity;
using Common;
using WCR_LMS.Models;

namespace WCR_LMS.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {

        private LMSDb db = new LMSDb();

        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> ClientList()
        {
            var clients = await db.Clients.ToListAsync();
            return View(clients);
        }

        [HttpGet]
        public ActionResult AddClient()
        {           
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Client client)
        {
            db.Clients.Add(client);
            await db.SaveChangesAsync();            

            return RedirectToAction("ClientList");
        }

        [HttpGet]
        public async Task<ActionResult> ViewClient(int id)
        {
            ClientViewModel client = new ClientViewModel();

            client.Client = await db.Clients.Where(c => c.Id == id).SingleAsync();
            client.Departments = await db.Departments.Where(d => d.ClientId == id).ToListAsync();
            
            return View(client);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateClient(ClientViewModel model)
        {
      

            var clients =  db.Clients.Find(model.Client.Id);

            clients.ClientName = model.Client.ClientName;
            clients.VendorNumber = model.Client.VendorNumber;
            clients.VATNumber = model.Client.VATNumber;
            clients.InvoiceAddress = model.Client.InvoiceAddress;
            clients.PhysicalAddress = model.Client.PhysicalAddress;
            clients.PostalCode = model.Client.PostalCode;

            db.SaveChanges();

            return RedirectToAction("ClientList");
        }

        [HttpGet]
        public async Task<ActionResult> EditClient(Client list)
        {
            ClientViewModel client = new ClientViewModel();

            client.Client = await db.Clients.Where(c => c.Id == list.Id).SingleAsync();

            return View(client);
        }
    }
}

WCR LMS/Views/Client/AddClient.cshtml
@model Common.Client
@{
    ViewBag.Title = "Add Client";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">New Client</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("Create", "Client", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))
        {
            @Html.AntiForgeryToken()
            <fieldset class="content-group">
                <legend class="text-bold">Client Information</legend>

                <div class="form-group">
                    @Html.LabelFor(model => model.ClientName, new { @class = "control-label col-lg-2" })
                    <div class="col-lg-10">
                        @Html.TextBoxFor(model => model.ClientName, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.ClientName)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VendorNumber, new { @class = "control-label col-lg-2" })
                    <div class="col-lg-10">
                        @Html.TextBoxFor(model => model.VendorNumber, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.VendorNumber)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VATNumber, new { @class = "control-label col-lg-2" })
                    <div class="col-lg-10">
                        @Html.TextBoxFor(model => model.VATNumber, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.VATNumber)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InvoiceAddress, new { @class = "control-label col-lg-2" })
                    <div class="col-lg-10">
                        @Html.TextAreaFor(model => model.InvoiceAddress, new { @class = "form-control", @cols = "4", @rows = "4", required = "required" })
                        @Html.ValidationMessageFor(model => model.InvoiceAddress)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhysicalAddress, new { @class = "control-label col-lg-2" })
                    <div class="col-lg-10">
                        @Html.TextAreaFor(model => model.PhysicalAddress, new { @class = "form-control", @cols = "4", @rows = "4", required = "required" })
                        @Html.ValidationMessageFor(model => model.PhysicalAddress)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PostalCode, new { @class = "control-label col-lg-2" })
                    <div class="col-lg-10">
                        @Html.TextBoxFor(model => model.PostalCode, new { @class = "form-control", required = "required", type = "tel" })
                        @Html.ValidationMessageFor(model => model.PostalCode)
                    </div>
                </div>
            </fieldset>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
            </div>
        }
    </div>
</div>

WCR LMS/Views/Client/ClientList.cshtml
@model List<Common.Client>
@{
    ViewBag.Title = "Client List";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Clients</h5>
        <div class="heading-elements">
            @Html.ActionLink("Add Client", "AddClient", null, new { @class = "btn btn-primary btn-xs" })
        </div>
    </div>

    <table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
        <thead>
            <tr>
                <th>Client Name</th>
                <th>Vendor Number</th>
                <th>VAT Number</th>
                <th class="text-center">Maintenance</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var client in Model)
            {
                <tr onclick="">
                    <td>@client.ClientName</td>
                    <td>@client.VendorNumber</td>
                    <td>@client.VATNumber</td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="@Url.Action("ViewClient", "Client", new { id = client.Id })" class="">View Departments for Client</a></li>
                                    <li><a href="@Url.Action("EditClient", "Client", new { id = client.Id })" class="">Edit Client</a></li>

                                </ul>
                            </li>
                        </ul>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {

    <script type="text/javascript">

    </script>

}

WCR LMS/Views/Client/EditClient.cshtml
@model WCR_LMS.Models.ClientViewModel
@{
    ViewBag.Title = "Edit Client Details";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Edit Client Client</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("UpdateClient", "Client", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))

    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.Client.Id)
        <fieldset class="content-group">
            <legend class="text-bold">Client Information</legend>

            <div class="form-group">
                @Html.LabelFor(model => model.Client.ClientName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Client.ClientName, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Client.ClientName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Client.VendorNumber, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Client.VendorNumber, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Client.VendorNumber)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Client.VATNumber, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Client.VATNumber, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Client.VATNumber)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Client.InvoiceAddress, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextAreaFor(model => model.Client.InvoiceAddress, new { @class = "form-control", @cols = "4", @rows = "4", required = "required" })
                    @Html.ValidationMessageFor(model => model.Client.InvoiceAddress)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Client.PhysicalAddress, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextAreaFor(model => model.Client.PhysicalAddress, new { @class = "form-control", @cols = "4", @rows = "4", required = "required" })
                    @Html.ValidationMessageFor(model => model.Client.PhysicalAddress)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Client.PostalCode, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Client.PostalCode, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Client.PostalCode)
                </div>
            </div>
        </fieldset>

        <div class="text-right">
            <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
        </div>
}
    </div>
</div>

WCR LMS/Views/Client/ViewClient.cshtml
@model WCR_LMS.Models.ClientViewModel
@{
    ViewBag.Title = "View Client";
}

<div class="panel panel-flat panel-collapse">
    <div class="panel-heading">
        <h5 class="panel-title">Client: <strong>@Model.Client.ClientName</strong></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <hr style="margin-top:0px; margin-bottom:0px;" />

    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Client.ClientName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.ClientName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Client.VendorNumber, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.VendorNumber</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Client.VATNumber, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.VATNumber</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Client.InvoiceAddress, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.InvoiceAddress</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Client.PhysicalAddress, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.PhysicalAddress</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Client.PostalCode, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.PostalCode</div>
                </div>
            </div>
        </div>


    </div>
</div>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Departments for <strong>@Model.Client.ClientName</strong></h5>

        <div class="heading-elements">
            <!--@Html.ActionLink("Add Department", "AddDepartment", "Department", new { clientId = Model.Client.Id }, new { @class = "btn btn-primary btn-xs" })            -->
        </div>
    </div>
    <hr style="margin-top:0px; margin-bottom:0px;" />
    <table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
        <thead>
            <tr>
                <th>Department Name</th>
                <th>Contact Person Name</th>
                <th>Designation</th>
                <th>Contact Person Email</th>
                <th>Contact Person Tel</th>
                <th class="text-center">Maintenance</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var department in Model.Departments)
            {
            <tr>
                <td>@department.DepartmentName</td>
                <td>@department.ContactPersonName</td>
                <td>@department.Designation</td>
                <td>@department.ContactPersonEmail</td>
                <td>@department.ContactPersonTel1</td>
                <td class="text-center">
                    <ul class="icons-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="@Url.Action("ViewDepartment", "Department", new { id = department.Id })" class="">View Department</a></li>                                
                                <li><a href="#" class="">Edit Department</a></li>

                            </ul>
                        </li>
                    </ul>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>