WCR LMS/Controllers/TenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WCR_LMS.DataContexts;
using System.Data;
using System.Data.Entity;
using Common;
using WCR_LMS.Models;

namespace WCR_LMS.Controllers
{
    [Authorize]
    public class TenderController : Controller
    {

        private LMSDb db = new LMSDb();

        // GET: Planning
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> TenderList()
        {
            var tenders = await db.TenderContract.ToListAsync();
            return View(tenders);
        }

        [HttpGet]
        public ActionResult AddTender()
        {
            ViewBag.Clients = db.Clients;
            
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(TenderContract tendercontract)
        {

            tendercontract.TenderContractDescription = tendercontract.TypeOfTraining + tendercontract.TenderCourseName + tendercontract.CourseDuration;
            tendercontract.LastUpdateDate = DateTime.Now.ToString();

            /*Temp --Remove*/
            tendercontract.ContractExpireDate = DateTime.Now.ToString();

            if (tendercontract.NonUnitStandard == null)
            { tendercontract.NonUnitStandard = 0; }
            else { tendercontract.SAQAUnitStandardID = 0; }

            db.TenderContract.Add(tendercontract);
            
            await db.SaveChangesAsync();            

            return RedirectToAction("TenderList");
        }

        [HttpGet]
        public async Task<ActionResult> ViewTender(int id)
        {
            TenderModel tender = new TenderModel();

            tender.TenderContract = await db.TenderContract.Where(c => c.Id == id).SingleAsync();
            tender.Client = await db.Clients.Where(c => c.Id == tender.TenderContract.ClientId).SingleAsync();
            
            return View(tender);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateTender(TenderModel model)
        {
      
            var tender =  db.TenderContract.Find(model.TenderContract.Id);

            tender.ClientId = model.TenderContract.ClientId;
            tender.TenderName = model.TenderContract.TenderName;
            tender.ContractNumber = model.TenderContract.ContractNumber;
            tender.TypeOfTraining = model.TenderContract.TypeOfTraining;
            tender.CourseDuration = model.TenderContract.CourseDuration;
            tender.SAQAUnitStandardID = model.TenderContract.SAQAUnitStandardID;
            tender.NonUnitStandard = model.TenderContract.NonUnitStandard;
            tender.TenderContractDescription = model.TenderContract.TypeOfTraining + model.TenderContract.TenderCourseName + model.TenderContract.CourseDuration;
            tender.ContractExpireDate = model.TenderContract.ContractExpireDate;
            tender.PriceExclVat = model.TenderContract.PriceExclVat;
            tender.LastUpdateDate = DateTime.Now.ToString();

            db.SaveChanges();

            return RedirectToAction("TenderList");
        }

        [HttpGet]
        public async Task<ActionResult> EditTender(Planning list)
        {
            TenderModel tender = new TenderModel();

            tender.TenderContract = await db.TenderContract.Where(c => c.Id == list.Id).SingleAsync();
            //client.Departments = await db.Departments.Where(d => d.ClientId == id).ToListAsync();

            ViewBag.Clients = db.Clients;
            ViewBag.ClientsId = new SelectList(db.Clients, "Id", "ClientName", tender.TenderContract.ClientId);

            return View(tender);
        }
    }
}

WCR LMS/Views/Tender/AddTender.cshtml
@model Common.TenderContract
@{
    ViewBag.Title = "Add Tender Contract";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">New Tender</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("Create", "Tender", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))
        {
            @Html.AntiForgeryToken()
        <fieldset class="content-group">
            <legend class="text-bold">Tender Information</legend>

            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label class="control-label col-lg-2">Client</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(n => n.ClientId, new SelectList(ViewBag.Clients, "Id", "ClientName", "1"))
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContractNumber, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContractNumber, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">Course Type</label>
                <div class="col-lg-10">
                    Accredited
                    @Html.RadioButtonFor(e => e.TypeOfTraining, "Accredited", new { id = "Accredited" })
                    Non Accredited
                    @Html.RadioButtonFor(e => e.TypeOfTraining, "Non Accredited", new { id = "Non Accredited" })
                    Attended
                    @Html.RadioButtonFor(e => e.TypeOfTraining, "Attended", new { id = "Attended" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderCourseName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderCourseName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseDuration, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.CourseDuration, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SAQAUnitStandardID, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.SAQAUnitStandardID, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NonUnitStandard, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.NonUnitStandard, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContractExpireDate, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContractExpireDate, "{0: MM/DD/yyyy}", new { @class = "form-control", @type = "date" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PriceExclVat, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PriceExclVat, new { @class = "form-control" })
                </div>
            </div>

        </fieldset>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
            </div>
        }
    </div>
</div>

WCR LMS/Views/Tender/EditTender.cshtml
@model WCR_LMS.Models.TenderModel
@{
    ViewBag.Title = "Edit Tender Details";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Edit Tender</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("UpdateTender", "Tender", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))

    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.TenderContract.Id)
        <fieldset class="content-group">
            <legend class="text-bold">Tender Information</legend>

            <div class="form-group">
                <label class="control-label col-lg-2">Client</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(n => n.TenderContract.ClientId, new SelectList(ViewBag.Clients, "Id", "ClientName", (SelectList)ViewBag.ClientId))
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.TenderName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.TenderName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.ContractNumber, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.ContractNumber, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">Course Type</label>
                <div class="col-lg-10">
                    Accredited
                    @Html.RadioButtonFor(e => e.TenderContract.TypeOfTraining, "Accredited", new { id = "Accredited" })
                    Non Accredited
                    @Html.RadioButtonFor(e => e.TenderContract.TypeOfTraining, "Non Accredited", new { id = "Non Accredited" })
                    Attended
                    @Html.RadioButtonFor(e => e.TenderContract.TypeOfTraining, "Attended", new { id = "Attended" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.TenderCourseName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.TenderCourseName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.CourseDuration, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.CourseDuration, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.SAQAUnitStandardID, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.SAQAUnitStandardID, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.NonUnitStandard, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.NonUnitStandard, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.ContractExpireDate, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.ContractExpireDate, "{0: MM/DD/yyyy}", new { @class = "form-control", @type = "date" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenderContract.PriceExclVat, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.TenderContract.PriceExclVat, new { @class = "form-control" })
                </div>
            </div>
        </fieldset>

        <div class="text-right">
            <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
        </div>
}
    </div>
</div>

WCR LMS/Views/Tender/TenderList.cshtml
@model List<Common.TenderContract>
@{
    ViewBag.Title = "Tender Contract List";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Tender Contracts</h5>
        <div class="heading-elements">
            @Html.ActionLink("Add Tender", "AddTender", null, new { @class = "btn btn-primary btn-xs" })
        </div>
    </div>

    <table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
        <thead>
            <tr>
                <th>Tender Name</th>
                <th>Tender Course Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var tender in Model)
            {
                <tr onclick="">
                    <td>@tender.TenderName</td>
                    <td>@tender.TenderCourseName</td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="@Url.Action("ViewTender", "Tender", new { id = tender.Id })" class="">View Tendor</a></li>
                                    <li><a href="@Url.Action("EditTender", "Tender", new { id = tender.Id })" class="">Edit Tendor</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {

    <script type="text/javascript">

    </script>

}

WCR LMS/Views/Tender/ViewTender.cshtml
@model WCR_LMS.Models.TenderModel
@{
    ViewBag.Title = "View Tender";
}

<div class="panel panel-flat panel-collapsed">
    <div class="panel-heading">
        <h5 class="panel-title">Tender: <strong>@Model.TenderContract.TenderName</strong></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <hr style="margin-top:0px; margin-bottom:0px;" />

    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Client.ClientName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.ClientName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.TenderName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.TenderName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.ContractNumber, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.ContractNumber</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.TypeOfTraining, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.TypeOfTraining</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.TenderCourseName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.TenderCourseName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.CourseDuration, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.CourseDuration</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.SAQAUnitStandardID, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.SAQAUnitStandardID</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.NonUnitStandard, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.NonUnitStandard</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.TenderContractDescription, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.TenderContractDescription</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.ContractExpireDate, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.ContractExpireDate</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.PriceExclVat, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.PriceExclVat</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TenderContract.LastUpdateDate, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.TenderContract.LastUpdateDate</div>
                </div>
            </div>
        </div>


    </div>
</div>
<!--
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Departments for <strong>Model.Client.ClientName</strong></h5>

        <div class="heading-elements">
            Html.ActionLink("Add Department", "AddDepartment", "Department", new { clientId = Model.Client.Id }, new { class = "btn btn-primary btn-xs" })            
        </div>
    </div>
<hr style="margin-top:0px; margin-bottom:0px;" />
<table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
    <thead>
        <tr>
            <th>Department Name</th>
            <th>Contact Person Name</th>
            <th>Designation</th>
            <th>Contact Person Email</th>
            <th>Contact Person Tel</th>
            <th class="text-center">Maintenance</th>
        </tr>
    </thead>
    <tbody>
        foreach (var department in Model.Departments)
        {
            <tr>
                <td>department.DepartmentName</td>
                <td>department.ContactPersonName</td>
                <td>department.Designation</td>
                <td>department.ContactPersonEmail</td>
                <td>department.ContactPersonTel1</td>
                <td class="text-center">
                    <ul class="icons-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="Url.Action("ViewDepartment", "Department", new { id = department.Id })" class="">View Department</a></li>
                                <li><a href="#" class="">Edit Department</a></li>

                            </ul>
                        </li>
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>-->