WCR LMS/Models/DepartmentViewModel.cs
using Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WCR_LMS.Models
{
    public class DepartmentViewModel
    {
        public int ClientId { get; set; }
        public Client Client { get; set; }
        public Department Department { get; set; }
        public List<Learner> Learners { get; set; }

    }
}

WCR LMS/Controllers/DepartmentController.cs
using Common;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WCR_LMS.DataContexts;
using WCR_LMS.Models;

namespace WCR_LMS.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {

        private LMSDb db = new LMSDb();

        [HttpGet]
        public async Task<ActionResult> DepartmentList()
        {
            var department = await db.Departments.ToListAsync();
            return View(department);
        }

        [HttpGet]
        public ActionResult AddDepartment()
        {
            ViewBag.Clients = db.Clients; 
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Department department)
        {
            
            db.Departments.Add(department);
            
            await db.SaveChangesAsync();

            return RedirectToAction("DepartmentList");
        }

        [HttpGet]
        public async Task<ActionResult> ViewDepartment(int id)
        {            
            DepartmentViewModel model = new DepartmentViewModel();

            ViewBag.Clients = db.Clients;
            model.Department = await db.Departments.Where(dep => dep.Id == id).SingleAsync();
            model.Client = await db.Clients.Where(client => client.Id == model.Department.ClientId).SingleAsync();
            model.Learners = await db.Learners.Where(learner => learner.DepartmentId == model.Department.Id).ToListAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateDepartment(DepartmentViewModel model)
        { 
            var department = db.Departments.Find(model.Department.Id);

            department.ClientId = model.Department.ClientId;
            department.DepartmentName = model.Department.DepartmentName;
            department.ContactPersonName = model.Department.ContactPersonName;
            department.Designation = model.Department.Designation;
            department.ContactPersonEmail = model.Department.ContactPersonEmail;
            department.ContactPersonTel1 = model.Department.ContactPersonTel1;
            department.ContactPersonTel2 = model.Department.ContactPersonTel2;
            department.ContactPersonFax = model.Department.ContactPersonFax;

            db.SaveChanges();

            return RedirectToAction("DepartmentList");
        }

        [HttpGet]
        public async Task<ActionResult> EditDepartment(Department list)
        {
            DepartmentViewModel model = new DepartmentViewModel();
            
            model.Department = await db.Departments.Where(c => c.Id == list.Id).SingleAsync();
            model.Client = await db.Clients.Where(client => client.Id == model.Department.ClientId).SingleAsync();

            ViewBag.Clients = db.Clients;
            ViewBag.ClientsId = new SelectList(db.Clients, "Id", "ClientName", model.Department.ClientId);
          
            return View(model);
        }
    }
}

WCR LMS/Views/Department/AddDepartment.cshtml
@model Common.Department
@{
    ViewBag.Title = "AddDepartment";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title"><strong>New Department</strong></h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("Create", "Department", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))
        {
            @Html.AntiForgeryToken()
            
        <fieldset class="content-group">

            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label class="control-label col-lg-2">Default Client</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(n => n.ClientId, new SelectList(ViewBag.Clients, "Id", "ClientName", "1"))
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.DepartmentName, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.DepartmentName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactPersonName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContactPersonName, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.ContactPersonName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactPersonEmail, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContactPersonEmail, new { @class = "form-control", required = "required", type = "email" })
                    @Html.ValidationMessageFor(model => model.ContactPersonEmail)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Designation, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Designation, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Designation)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactPersonTel1, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContactPersonTel1, new { @class = "form-control", required = "required", type = "tel" })
                    @Html.ValidationMessageFor(model => model.ContactPersonTel1)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactPersonTel2, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContactPersonTel2, new { @class = "form-control", type = "tel" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactPersonFax, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContactPersonFax, new { @class = "form-control", type = "tel" })
                </div>
            </div>

        </fieldset>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
            </div>
        }
    </div>
</div>

WCR LMS/Views/Department/DepartmentList.cshtml
@model List<Common.Department>
@{
    ViewBag.Title = "Department List";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Department</h5>
        <div class="heading-elements">
            @Html.ActionLink("Add Department", "AddDepartment", null, new { @class = "btn btn-primary btn-xs" })
        </div>
    </div>

    <table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
        <thead>
            <tr>
                <th>Department Name</th>
                <th>Contact Person</th>
                <th>Client ID</th>
                <th class="text-center">Maintenance</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var department in Model)
            {
                <tr onclick="">
                    <td>@department.DepartmentName</td>
                    <td>@department.ContactPersonName</td>
                    <td>@department.ClientId</td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="@Url.Action("ViewDepartment", "Department", new { id = department.Id })" class="">View Learners for Department</a></li>
                                    <li><a href="@Url.Action("EditDepartment", "Department", new { id = department.Id })" class="">Edit Department</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {

    <script type="text/javascript">

    </script>

}

WCR LMS/Views/Department/EditDepartment.cshtml
@model WCR_LMS.Models.DepartmentViewModel
@{
    ViewBag.Title = "Edit Department Details";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Edit Department Client</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("UpdateDepartment", "Department", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))

    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.Department.Id)
        <fieldset class="content-group">
            <legend class="text-bold">Department Information</legend>

            <div class="form-group">
                <label class="control-label col-lg-2">Default Client</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(n => n.Department.ClientId, new SelectList(ViewBag.Clients, "Id", "ClientName", (SelectList)ViewBag.ClientsId))
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.DepartmentName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.DepartmentName, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Department.DepartmentName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.ContactPersonName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.ContactPersonName, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Department.ContactPersonName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.Designation, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.Designation, new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.Department.Designation)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.ContactPersonEmail, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.ContactPersonEmail, new { @class = "form-control", required = "required", type = "email" })
                    @Html.ValidationMessageFor(model => model.Department.ContactPersonEmail)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.ContactPersonTel1, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.ContactPersonTel1, new { @class = "form-control", required = "required", type = "tel" })
                    @Html.ValidationMessageFor(model => model.Department.ContactPersonTel1)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.ContactPersonTel2, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.ContactPersonTel2, new { @class = "form-control", required = "required", type = "tel" })
                    @Html.ValidationMessageFor(model => model.Department.ContactPersonTel2)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department.ContactPersonFax, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.Department.ContactPersonFax, new { @class = "form-control", required = "required", type = "tel" })
                    @Html.ValidationMessageFor(model => model.Department.ContactPersonFax)
                </div>
            </div>

        </fieldset>

        <div class="text-right">
            <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
        </div>
}
    </div>
</div>

WCR LMS/Views/Department/ViewDepartment.cshtml
@model WCR_LMS.Models.DepartmentViewModel
@{
    ViewBag.Title = "View Department";
}

<div class="panel panel-flat panel-collapse">
    <div class="panel-heading">
        <h5 class="panel-title">Department: <strong>@Model.Department.DepartmentName</strong></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <!--<li>Html.ActionLink("Add Learner", "AddLearner", "Learner", new { Id = Model.Department.Id }, new { class = "btn btn-primary btn-xs" })</li>-->
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <hr style="margin-top:0px; margin-bottom:0px;" />

    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Client.ClientName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.ClientName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Department.DepartmentName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Department.DepartmentName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Department.ContactPersonEmail, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Department.ContactPersonEmail</div>
                </div>

            </div>

            <div class="col-md-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.Department.ContactPersonTel1, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Department.ContactPersonTel1</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Department.ContactPersonTel1, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Department.ContactPersonTel2</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Department.ContactPersonFax, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Department.ContactPersonFax</div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Learners for Department: <strong>@Model.Department.DepartmentName</strong></h5>

        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <hr style="margin-top:0px; margin-bottom:0px;" />
    <table class="table datatable-save-state datatable-basic table-hover" id="learnersTable">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Cellphone</th>
                <th class="text-center">Maintenance</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var learner in Model.Learners)
            {
                <tr>
                    <td>@learner.FirstName</td>
                    <td>@learner.LastName</td>
                    <td>@learner.Email</td>
                    <td>@learner.TelNumber</td>
                    <td>@learner.CellNumber</td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="@Url.Action("ViewLearner", "Learner", new { id = learner.Id })" class="">View Learner</a></li>
                                    <li><a href="#" class="">Edit Learner</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>