WCR LMS/Controllers/PrivateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WCR_LMS.DataContexts;
using System.Data;
using System.Data.Entity;
using Common;
using WCR_LMS.Models;

namespace WCR_LMS.Controllers
{
    [Authorize]
    public class PrivateController : Controller
    {

        private LMSDb db = new LMSDb();

        // GET: Planning
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> PrivateList()
        {
            var Privates = await db.PrivateContract.ToListAsync();
            return View(Privates);
        }

        [HttpGet]
        public ActionResult AddPrivate()
        {
            ViewBag.Clients = db.Clients;
            
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(PrivateContract Privatecontract)
        {

            Privatecontract.PrivateContractDescription = Privatecontract.TypeOfTraining + Privatecontract.PrivateCourseName + Privatecontract.CourseDuration;
            Privatecontract.LastUpdateDate = DateTime.Now.ToString();

            /*Temp --Remove*/
            Privatecontract.ContractExpireDate = DateTime.Now.ToString();

            db.PrivateContract.Add(Privatecontract);
            
            await db.SaveChangesAsync();            

            return RedirectToAction("PrivateList");
        }

        [HttpGet]
        public async Task<ActionResult> ViewPrivate(int id)
        {
            PrivateModel Private = new PrivateModel();

            Private.PrivateContract = await db.PrivateContract.Where(c => c.Id == id).SingleAsync();
            Private.Client = await db.Clients.Where(c => c.Id == Private.PrivateContract.ClientId).SingleAsync();
            
            return View(Private);
        }

        [HttpPost]
        public async Task<ActionResult> UpdatePrivate(PrivateModel model)
        {
      
            var Private =  db.PrivateContract.Find(model.PrivateContract.Id);

            Private.ClientId = model.PrivateContract.ClientId;
            Private.PrivateName = model.PrivateContract.PrivateName;
            Private.TypeOfTraining = model.PrivateContract.TypeOfTraining;
            Private.CourseDuration = model.PrivateContract.CourseDuration;
            Private.SAQAUnitStandardID = model.PrivateContract.SAQAUnitStandardID;
            Private.NonUnitStandard = model.PrivateContract.NonUnitStandard;
            Private.PrivateContractDescription = model.PrivateContract.TypeOfTraining + model.PrivateContract.PrivateCourseName + model.PrivateContract.CourseDuration;
            Private.ContractExpireDate = model.PrivateContract.ContractExpireDate;
            Private.PriceExclVat = model.PrivateContract.PriceExclVat;
            Private.LastUpdateDate = DateTime.Now.ToString();

            db.SaveChanges();

            return RedirectToAction("PrivateList");
        }

        [HttpGet]
        public async Task<ActionResult> EditPrivate(Planning list)
        {
            PrivateModel Private = new PrivateModel();

            Private.PrivateContract = await db.PrivateContract.Where(c => c.Id == list.Id).SingleAsync();

            ViewBag.Clients = db.Clients;
            ViewBag.ClientsId = new SelectList(db.Clients, "Id", "ClientName", Private.PrivateContract.ClientId);

            return View(Private);
        }
    }
}

WCR LMS/Views/Private/AddPrivate.cshtml
@model Common.PrivateContract
@{
    ViewBag.Title = "Add Private Contract";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">New Private</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("Create", "Private", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))
        {
            @Html.AntiForgeryToken()
        <fieldset class="content-group">
            <legend class="text-bold">Private Information</legend>
            
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label class="control-label col-lg-2">Client</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(n => n.ClientId, new SelectList(ViewBag.Clients, "Id", "ClientName", "1"))
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">Course Type</label>
                <div class="col-lg-10">
                    Accredited
                    @Html.RadioButtonFor(e => e.TypeOfTraining, "Accredited", new { id = "Accredited" })
                    Non Accredited
                    @Html.RadioButtonFor(e => e.TypeOfTraining, "Non Accredited", new { id = "Non Accredited" })
                    Attended
                    @Html.RadioButtonFor(e => e.TypeOfTraining, "Attended", new { id = "Attended" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateCourseName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateCourseName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseDuration, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.CourseDuration, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SAQAUnitStandardID, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.SAQAUnitStandardID, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NonUnitStandard, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.NonUnitStandard, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContractExpireDate, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.ContractExpireDate, "{0: yyyy/DD/mm}", new { @class = "form-control", @type = "date" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PriceExclVat, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PriceExclVat, new { @class = "form-control" })
                </div>
            </div>

        </fieldset>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
            </div>
        }
    </div>
</div>

WCR LMS/Views/Private/EditPrivate.cshtml
@model WCR_LMS.Models.PrivateModel
@{
    ViewBag.Title = "Edit Private Details";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Edit Private</h5>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm("UpdatePrivate", "Private", FormMethod.Post, new { @class = "form-horizontal", id = "form", name = "form" }))

    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.PrivateContract.Id)
        <fieldset class="content-group">
            <legend class="text-bold">Private Information</legend>

            <div class="form-group">
                <label class="control-label col-lg-2">Client</label>
                <div class="col-lg-10">
                    @Html.DropDownListFor(n => n.PrivateContract.ClientId, new SelectList(ViewBag.Clients, "Id", "ClientName", (SelectList)ViewBag.ClientId))
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.PrivateName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.PrivateName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">Course Type</label>
                <div class="col-lg-10">
                    Accredited
                    @Html.RadioButtonFor(e => e.PrivateContract.TypeOfTraining, "Accredited", new { id = "Accredited" })
                    Non Accredited
                    @Html.RadioButtonFor(e => e.PrivateContract.TypeOfTraining, "Non Accredited", new { id = "Non Accredited" })
                    Attended
                    @Html.RadioButtonFor(e => e.PrivateContract.TypeOfTraining, "Attended", new { id = "Attended" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.PrivateCourseName, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.PrivateCourseName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.CourseDuration, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.CourseDuration, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.SAQAUnitStandardID, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.SAQAUnitStandardID, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.NonUnitStandard, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.NonUnitStandard, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.ContractExpireDate, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.ContractExpireDate, "{0: yyyy/DD/mm}", new { @class = "form-control", @type = "date" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrivateContract.PriceExclVat, new { @class = "control-label col-lg-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.PrivateContract.PriceExclVat, new { @class = "form-control" })
                </div>
            </div>
        </fieldset>

        <div class="text-right">
            <button type="submit" class="btn btn-primary">Submit<i class="icon-arrow-right14 position-right"></i></button>
        </div>
}
    </div>
</div>

WCR LMS/Views/Private/PrivateList.cshtml
@model List<Common.PrivateContract>
@{
    ViewBag.Title = "Private Contract List";
}

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Private Contracts</h5>
        <div class="heading-elements">
            @Html.ActionLink("Add Private", "AddPrivate", null, new { @class = "btn btn-primary btn-xs" })
        </div>
    </div>

    <table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
        <thead>
            <tr>
                <th>Private Name</th>
                <th>Private Course Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Private in Model)
            {
                <tr onclick="">
                    <td>@Private.PrivateName</td>
                    <td>@Private.PrivateCourseName</td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="@Url.Action("ViewPrivate", "Private", new { id = Private.Id })" class="">View Private</a></li>
                                    <li><a href="@Url.Action("EditPrivate", "Private", new { id = Private.Id })" class="">Edit Private</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {

    <script type="text/javascript">

    </script>

}

WCR LMS/Views/Private/ViewPrivate.cshtml
@model WCR_LMS.Models.PrivateModel
@{
    ViewBag.Title = "View Private";
}

<div class="panel panel-flat panel-collapsed">
    <div class="panel-heading">
        <h5 class="panel-title">Private: <strong>@Model.PrivateContract.PrivateName</strong></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <hr style="margin-top:0px; margin-bottom:0px;" />

    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Client.ClientName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.Client.ClientName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.PrivateName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.PrivateName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.TypeOfTraining, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.TypeOfTraining</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.PrivateCourseName, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.PrivateCourseName</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.CourseDuration, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.CourseDuration</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.SAQAUnitStandardID, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.SAQAUnitStandardID</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.NonUnitStandard, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.NonUnitStandard</div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.PrivateContractDescription, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.PrivateContractDescription</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.ContractExpireDate, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.ContractExpireDate</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.PriceExclVat, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.PriceExclVat</div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PrivateContract.LastUpdateDate, new { @class = "text-semibold" })
                    <div class="form-control-static">@Model.PrivateContract.LastUpdateDate</div>
                </div>
            </div>
        </div>


    </div>
</div>
<!--
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Departments for <strong>Model.Client.ClientName</strong></h5>

        <div class="heading-elements">
            Html.ActionLink("Add Department", "AddDepartment", "Department", new { clientId = Model.Client.Id }, new { class = "btn btn-primary btn-xs" })            
        </div>
    </div>
<hr style="margin-top:0px; margin-bottom:0px;" />
<table class="table datatable-save-state datatable-basic table-hover" id="clientTable">
    <thead>
        <tr>
            <th>Department Name</th>
            <th>Contact Person Name</th>
            <th>Designation</th>
            <th>Contact Person Email</th>
            <th>Contact Person Tel</th>
            <th class="text-center">Maintenance</th>
        </tr>
    </thead>
    <tbody>
        foreach (var department in Model.Departments)
        {
            <tr>
                <td>department.DepartmentName</td>
                <td>department.ContactPersonName</td>
                <td>department.Designation</td>
                <td>department.ContactPersonEmail</td>
                <td>department.ContactPersonTel1</td>
                <td class="text-center">
                    <ul class="icons-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="Url.Action("ViewDepartment", "Department", new { id = department.Id })" class="">View Department</a></li>
                                <li><a href="#" class="">Edit Department</a></li>

                            </ul>
                        </li>
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>-->